import { getClient } from '../db/poolManager.js';
import { log } from '../config/logging.js';

// User-scoped, provider-stamped entry tables that carry a `source` column.
// Every table here has ON DELETE CASCADE children (e.g. exercise_entry_sets,
// sleep_entry_stages, exercise_entries linked to a preset entry), so a single
// `DELETE ... WHERE user_id AND source` cleans up the whole subtree.
//
// This list is a hardcoded whitelist and is the ONLY place table identifiers
// are interpolated into SQL below — never widen it with caller-provided input.
//
// Order matters for deletion: exercise_preset_entries must be removed before
// exercise_entries so the preset session and its cascade-linked child entries
// are cleaned up first, avoiding orphaned preset rows.
const SYNCED_SOURCE_TABLES = [
  'food_entries',
  'exercise_preset_entries',
  'exercise_entries',
  'sleep_entries',
  'custom_measurements',
  'water_intake',
  'water_intake_entries',
] as const;

type SyncedSourceTable = (typeof SYNCED_SOURCE_TABLES)[number];

// Source values that represent data the USER created themselves (not synced or
// imported from an external provider), and so must never be surfaced or deleted
// by this by-source cleanup tool:
//   - 'manual'          : typed in from web/mobile (most tables)
//   - 'sparky'          : logged via the Sparky AI assistant / chatbot
//   - 'workout preset'  : workout logged from a saved preset (exercise entries)
//   - 'workout plan'    : diary entries generated by a scheduled workout plan
// NOTE: the app is inconsistent about casing — exercise_entries default to
// 'Manual' (capital M), and the preset/plan values are Title Case, while other
// tables use lowercase 'manual'. So every comparison is done case-insensitively
// (LOWER(source) in SQL, toLowerCase() in JS). This is a denylist: if a NEW
// user-originated source tag is ever introduced in the app, add it here so it
// is not offered for deletion.
const USER_ORIGINATED_SOURCES = [
  'manual',
  'sparky',
  'workout preset',
  'workout plan',
] as const;

// True when a source string represents user-created data, regardless of casing.
const isUserOriginatedSource = (source: string | null | undefined): boolean =>
  USER_ORIGINATED_SOURCES.includes(
    (source ?? '')
      .trim()
      .toLowerCase() as (typeof USER_ORIGINATED_SOURCES)[number]
  );

export interface SyncedSourceSummary {
  source: string;
  totalCount: number;
  byTable: Partial<Record<SyncedSourceTable, number>>;
}

// Returns one entry per distinct provider `source` the user has synced data
// for, with a per-table breakdown of how many rows carry that source.
// User-originated sources (manual / workout preset / workout plan) and NULL are
// excluded so this can never surface — or later delete — data the user created
// themselves.
async function getSyncedSourceSummary(
  userId: string
): Promise<SyncedSourceSummary[]> {
  const client = await getClient(userId);
  try {
    const summary = new Map<string, SyncedSourceSummary>();
    for (const table of SYNCED_SOURCE_TABLES) {
      const result = await client.query(
        `SELECT source, COUNT(*)::int AS count
           FROM ${table}
          WHERE user_id = $1
            AND source IS NOT NULL
            AND LOWER(source) <> ALL($2::text[])
          GROUP BY source`,
        [userId, USER_ORIGINATED_SOURCES]
      );
      for (const row of result.rows) {
        const source: string = row.source;
        const count: number = row.count;
        const existing = summary.get(source) ?? {
          source,
          totalCount: 0,
          byTable: {},
        };
        existing.totalCount += count;
        existing.byTable[table] = count;
        summary.set(source, existing);
      }
    }
    return Array.from(summary.values()).sort(
      (a, b) => b.totalCount - a.totalCount
    );
  } finally {
    client.release();
  }
}

// Deletes every row across the synced entry tables that carries the given
// `source`, for this user only, in a single transaction. Refuses any
// user-originated source (manual / workout preset / workout plan). Returns the
// per-table deleted-row counts.
async function deleteSyncedDataBySource(
  userId: string,
  source: string
): Promise<{ byTable: Record<string, number>; totalDeleted: number }> {
  if (isUserOriginatedSource(source)) {
    throw new Error(
      `Refusing to bulk-delete user-created data (source '${source}').`
    );
  }
  const client = await getClient(userId);
  try {
    await client.query('BEGIN');
    const byTable: Record<string, number> = {};
    let totalDeleted = 0;
    for (const table of SYNCED_SOURCE_TABLES) {
      const result = await client.query(
        `DELETE FROM ${table} WHERE user_id = $1 AND source = $2`,
        [userId, source]
      );
      const deleted = result.rowCount ?? 0;
      byTable[table] = deleted;
      totalDeleted += deleted;
    }
    await client.query('COMMIT');
    log(
      'info',
      `[syncedData] Deleted ${totalDeleted} synced rows with source '${source}' for user ${userId}.`,
      byTable
    );
    return { byTable, totalDeleted };
  } catch (error) {
    await client.query('ROLLBACK');
    log(
      'error',
      `[syncedData] Error deleting synced data for source '${source}', user ${userId}:`,
      error
    );
    throw error;
  } finally {
    client.release();
  }
}

export {
  SYNCED_SOURCE_TABLES,
  USER_ORIGINATED_SOURCES,
  isUserOriginatedSource,
  getSyncedSourceSummary,
  deleteSyncedDataBySource,
};
